// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go

// Package mock_repo is a generated GoMock package.
package mock_repo

import (
	context "context"
	reflect "reflect"
	entity "room-booking-service/internal/entity"
	time "time"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// AddSlots mocks base method.
func (m *MockRepo) AddSlots(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSlots", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSlots indicates an expected call of AddSlots.
func (mr *MockRepoMockRecorder) AddSlots(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSlots", reflect.TypeOf((*MockRepo)(nil).AddSlots), ctx)
}

// CancelBooking mocks base method.
func (m *MockRepo) CancelBooking(ctx context.Context, userId, bookingId uuid.UUID) (*entity.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelBooking", ctx, userId, bookingId)
	ret0, _ := ret[0].(*entity.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelBooking indicates an expected call of CancelBooking.
func (mr *MockRepoMockRecorder) CancelBooking(ctx, userId, bookingId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelBooking", reflect.TypeOf((*MockRepo)(nil).CancelBooking), ctx, userId, bookingId)
}

// CreateBooking mocks base method.
func (m *MockRepo) CreateBooking(ctx context.Context, booking *entity.Booking) (uuid.UUID, *time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBooking", ctx, booking)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(*time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateBooking indicates an expected call of CreateBooking.
func (mr *MockRepoMockRecorder) CreateBooking(ctx, booking interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBooking", reflect.TypeOf((*MockRepo)(nil).CreateBooking), ctx, booking)
}

// CreateRoom mocks base method.
func (m *MockRepo) CreateRoom(ctx context.Context, room *entity.Room) (uuid.UUID, *time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoom", ctx, room)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(*time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateRoom indicates an expected call of CreateRoom.
func (mr *MockRepoMockRecorder) CreateRoom(ctx, room interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoom", reflect.TypeOf((*MockRepo)(nil).CreateRoom), ctx, room)
}

// CreateSchedule mocks base method.
func (m *MockRepo) CreateSchedule(ctx context.Context, schedule *entity.Schedule) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSchedule", ctx, schedule)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSchedule indicates an expected call of CreateSchedule.
func (mr *MockRepoMockRecorder) CreateSchedule(ctx, schedule interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSchedule", reflect.TypeOf((*MockRepo)(nil).CreateSchedule), ctx, schedule)
}

// GetBookings mocks base method.
func (m *MockRepo) GetBookings(ctx context.Context, page, pageSize int) ([]*entity.Booking, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookings", ctx, page, pageSize)
	ret0, _ := ret[0].([]*entity.Booking)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBookings indicates an expected call of GetBookings.
func (mr *MockRepoMockRecorder) GetBookings(ctx, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookings", reflect.TypeOf((*MockRepo)(nil).GetBookings), ctx, page, pageSize)
}

// GetBookingsUser mocks base method.
func (m *MockRepo) GetBookingsUser(ctx context.Context, userId uuid.UUID) ([]*entity.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingsUser", ctx, userId)
	ret0, _ := ret[0].([]*entity.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingsUser indicates an expected call of GetBookingsUser.
func (mr *MockRepoMockRecorder) GetBookingsUser(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingsUser", reflect.TypeOf((*MockRepo)(nil).GetBookingsUser), ctx, userId)
}

// GetRooms mocks base method.
func (m *MockRepo) GetRooms(ctx context.Context) ([]*entity.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRooms", ctx)
	ret0, _ := ret[0].([]*entity.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRooms indicates an expected call of GetRooms.
func (mr *MockRepoMockRecorder) GetRooms(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRooms", reflect.TypeOf((*MockRepo)(nil).GetRooms), ctx)
}

// GetSlots mocks base method.
func (m *MockRepo) GetSlots(ctx context.Context, roomId uuid.UUID, date time.Time) ([]*entity.Slot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSlots", ctx, roomId, date)
	ret0, _ := ret[0].([]*entity.Slot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSlots indicates an expected call of GetSlots.
func (mr *MockRepoMockRecorder) GetSlots(ctx, roomId, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSlots", reflect.TypeOf((*MockRepo)(nil).GetSlots), ctx, roomId, date)
}

// IsRoomExist mocks base method.
func (m *MockRepo) IsRoomExist(ctx context.Context, roomId uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRoomExist", ctx, roomId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsRoomExist indicates an expected call of IsRoomExist.
func (mr *MockRepoMockRecorder) IsRoomExist(ctx, roomId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRoomExist", reflect.TypeOf((*MockRepo)(nil).IsRoomExist), ctx, roomId)
}

// IsSlotInPast mocks base method.
func (m *MockRepo) IsSlotInPast(ctx context.Context, slotId uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSlotInPast", ctx, slotId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSlotInPast indicates an expected call of IsSlotInPast.
func (mr *MockRepoMockRecorder) IsSlotInPast(ctx, slotId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSlotInPast", reflect.TypeOf((*MockRepo)(nil).IsSlotInPast), ctx, slotId)
}
