ALTER TABLE users DROP CONSTRAINT IF EXISTS proper_email;
ALTER TABLE schedules DROP CONSTRAINT IF EXISTS check_times;
ALTER TABLE slots DROP CONSTRAINT IF EXISTS check_times;

DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS slots;
DROP TABLE IF EXISTS schedules;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS rooms;


DROP TYPE IF EXISTS role;
DROP TYPE IF EXISTS status;