// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"
	entity "room-booking-service/internal/entity"
	time "time"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockBookingService is a mock of BookingService interface.
type MockBookingService struct {
	ctrl     *gomock.Controller
	recorder *MockBookingServiceMockRecorder
}

// MockBookingServiceMockRecorder is the mock recorder for MockBookingService.
type MockBookingServiceMockRecorder struct {
	mock *MockBookingService
}

// NewMockBookingService creates a new mock instance.
func NewMockBookingService(ctrl *gomock.Controller) *MockBookingService {
	mock := &MockBookingService{ctrl: ctrl}
	mock.recorder = &MockBookingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingService) EXPECT() *MockBookingServiceMockRecorder {
	return m.recorder
}

// AddSlots mocks base method.
func (m *MockBookingService) AddSlots(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddSlots", ctx)
}

// AddSlots indicates an expected call of AddSlots.
func (mr *MockBookingServiceMockRecorder) AddSlots(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSlots", reflect.TypeOf((*MockBookingService)(nil).AddSlots), ctx)
}

// CancelBooking mocks base method.
func (m *MockBookingService) CancelBooking(ctx context.Context, userId, bookingId uuid.UUID) (*entity.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelBooking", ctx, userId, bookingId)
	ret0, _ := ret[0].(*entity.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelBooking indicates an expected call of CancelBooking.
func (mr *MockBookingServiceMockRecorder) CancelBooking(ctx, userId, bookingId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelBooking", reflect.TypeOf((*MockBookingService)(nil).CancelBooking), ctx, userId, bookingId)
}

// CreateBooking mocks base method.
func (m *MockBookingService) CreateBooking(ctx context.Context, booking *entity.Booking) (*entity.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBooking", ctx, booking)
	ret0, _ := ret[0].(*entity.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBooking indicates an expected call of CreateBooking.
func (mr *MockBookingServiceMockRecorder) CreateBooking(ctx, booking interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBooking", reflect.TypeOf((*MockBookingService)(nil).CreateBooking), ctx, booking)
}

// CreateRoom mocks base method.
func (m *MockBookingService) CreateRoom(ctx context.Context, room *entity.Room) (*entity.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoom", ctx, room)
	ret0, _ := ret[0].(*entity.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRoom indicates an expected call of CreateRoom.
func (mr *MockBookingServiceMockRecorder) CreateRoom(ctx, room interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoom", reflect.TypeOf((*MockBookingService)(nil).CreateRoom), ctx, room)
}

// CreateSchedule mocks base method.
func (m *MockBookingService) CreateSchedule(ctx context.Context, schedule *entity.Schedule) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSchedule", ctx, schedule)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSchedule indicates an expected call of CreateSchedule.
func (mr *MockBookingServiceMockRecorder) CreateSchedule(ctx, schedule interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSchedule", reflect.TypeOf((*MockBookingService)(nil).CreateSchedule), ctx, schedule)
}

// GetBookings mocks base method.
func (m *MockBookingService) GetBookings(ctx context.Context, page, pageSize int) ([]*entity.Booking, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookings", ctx, page, pageSize)
	ret0, _ := ret[0].([]*entity.Booking)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBookings indicates an expected call of GetBookings.
func (mr *MockBookingServiceMockRecorder) GetBookings(ctx, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookings", reflect.TypeOf((*MockBookingService)(nil).GetBookings), ctx, page, pageSize)
}

// GetBookingsUser mocks base method.
func (m *MockBookingService) GetBookingsUser(ctx context.Context, userId uuid.UUID) ([]*entity.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingsUser", ctx, userId)
	ret0, _ := ret[0].([]*entity.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingsUser indicates an expected call of GetBookingsUser.
func (mr *MockBookingServiceMockRecorder) GetBookingsUser(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingsUser", reflect.TypeOf((*MockBookingService)(nil).GetBookingsUser), ctx, userId)
}

// GetRooms mocks base method.
func (m *MockBookingService) GetRooms(ctx context.Context) ([]*entity.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRooms", ctx)
	ret0, _ := ret[0].([]*entity.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRooms indicates an expected call of GetRooms.
func (mr *MockBookingServiceMockRecorder) GetRooms(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRooms", reflect.TypeOf((*MockBookingService)(nil).GetRooms), ctx)
}

// GetSlots mocks base method.
func (m *MockBookingService) GetSlots(ctx context.Context, roomId uuid.UUID, date time.Time) ([]*entity.Slot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSlots", ctx, roomId, date)
	ret0, _ := ret[0].([]*entity.Slot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSlots indicates an expected call of GetSlots.
func (mr *MockBookingServiceMockRecorder) GetSlots(ctx, roomId, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSlots", reflect.TypeOf((*MockBookingService)(nil).GetSlots), ctx, roomId, date)
}

// IsRoomExist mocks base method.
func (m *MockBookingService) IsRoomExist(ctx context.Context, roomId uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRoomExist", ctx, roomId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsRoomExist indicates an expected call of IsRoomExist.
func (mr *MockBookingServiceMockRecorder) IsRoomExist(ctx, roomId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRoomExist", reflect.TypeOf((*MockBookingService)(nil).IsRoomExist), ctx, roomId)
}

// IsSlotInPast mocks base method.
func (m *MockBookingService) IsSlotInPast(ctx context.Context, slotId uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSlotInPast", ctx, slotId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSlotInPast indicates an expected call of IsSlotInPast.
func (mr *MockBookingServiceMockRecorder) IsSlotInPast(ctx, slotId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSlotInPast", reflect.TypeOf((*MockBookingService)(nil).IsSlotInPast), ctx, slotId)
}
